### ISSUE TITLE
Allow to ignore the text available in QAction

### ISSUE THREAD

**Issue by asemke** [KDAB/KDMacTouchBar#1]
I have a set of QActions used in the main menu and also in the toolbar and I want/need to re-use those actions in the TouchBar. Because of the limited amount of space showing the text in the touchbar is not always practical. It would be great to have an option in KDMacTouchBar to ignore the text available in QAction::text(). Maybe something similar to what we have in KF5's toolbar already with "Show Icon only", "Show Text only", "Show Icon an Text"?

**Comment by cschleifenbaum** [comment]
Thank you for your input, will add!

**Comment by cschleifenbaum** [comment]
Implemented. Please give feedback whether this fits your needs!

**Comment by asemke** [comment]
works fine, I just pushed  https://invent.kde.org/kde/labplot/commit/38f5d40d5127256d4ffcf827d3493203275c9cad . Thanks!

The icons set via KDMacTouchbar seems to be smaller compared to Mac's "native" icons:
https://ibb.co/DbXyzRM
https://ibb.co/g4JnFPJ

Those are SVG icons from the breeze iconset. The size of the icons as shown in the toolbar is ok. I'm not sure whether this is a problem of KDMacTouchBar or not...

Also, I need to think about the color of the icons. Black theme is ok when using light desktop color scheme. But for the touchbar I have to use the icons from breeze-dark probably. This won't make the re-use of QActions in the code as easy as I hoped...

**Comment by cschleifenbaum** [comment]
I don't know how big they icons you use are, but the example in the repository looks like that on my computer, and It think that's fine: https://www.kdab.com/wp-content/uploads/stories/IMG_0350-w-Qt-QMacTouchBar-300x225@2x.jpg

**Comment by cschleifenbaum** [comment]
The icon is quite big, 59x71px. Note that the display there is a retina display, though!
