### ISSUE TITLE
macOS Sonoma

### ISSUE THREAD

**Issue by heissmarkus** [KDAB/KDMacTouchBar#10]
Running the example with macOS Sonoma the touchbar stays empty / nothing is visible.

**Comment by cschleifenbaum** [comment]
Sorry for the late response. I'll have a look!

**Comment by cschleifenbaum** [comment]
@heissmarkus now after I updated my MacBook to Sonoma I had a test. And it is working as expected. Do you get any console output or anything?

**Comment by iamsergio** [comment]
reopen when needed
