### ISSUE TITLE
Add KDMacTouchBar::clear()

### ISSUE THREAD

**Issue by asemke** [KDAB/KDMacTouchBar#2]
I don't see any option at moment to clear the touchbar other than
` 
for (auto* action : m_touchBar->actions();
    m_touchBar->removeAction(action);
`

It would be great to have KDMacTouchBar::clear() to have a similar interface like in QToolBar.

**Comment by cschleifenbaum** [comment]
Thank you for your input, will add!

**Comment by cschleifenbaum** [comment]
Implemented.
